services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    #user: 1000:1000
    ports:
      - "8080:80"
    volumes:
      - uploads:/srv # files will be stored here
    restart: unless-stopped
  proccessor:
    image: processing_server
    build:
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - uploads:/uploads
    restart: unless-stopped
volumes:
  uploads:
